
services:
 
  php8:
    build: .
    container_name: app_projectClassRoom
    restart: always
    volumes:
      - ../:/var/www/html/
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal start_with_request=yes
  
 
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql_db

  mysql_db: 
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always 
    environment: 
      - MYSQL_ROOT_PASSWORD= p@ssw0rd
      - MYSQL_DATABASE= openclassroom
      - MYSQL_ALLOW_EMPTY_PASSWORD= 'true'
      - MYSQL_ALLOW_EMPTY_PASSWORD=1,   
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-data:
